// GENERATED by split_cases.py — do not edit by hand.
// Public half: what a student may see. No outcomes live here.

const SV = (s,f,a) => '<svg viewBox="0 0 32 32" stroke="rgba(0,0,0,.30)" stroke-width="1.1" '
  + 'stroke-linejoin="round" stroke-linecap="round">'
  + s.replace(/@f/g, f).replace(/@a/g, a) + '</svg>';
const W = 'rgba(255,255,255,.88)';
export const ICONS = {
  // trigger spray bottle
  spray: (f,a) => SV('<path d="M12 29h8a2 2 0 0 0 2-2V16a2 2 0 0 0-2-2h-8a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2Z" fill="@f"/>'
        + '<path d="M10 19h12v4H10Z" fill="'+W+'" stroke="none"/>'
        + '<path d="M13.5 14v-3h5v3" fill="@a"/>'
        + '<path d="M15 11V7h5l2.5 2v2h-7Z" fill="@a"/>'
        + '<path d="M25.5 6.5l2-1M26 9h2M25.5 11.5l1.8 1" fill="none" stroke="@a" stroke-width="1.3"/>', f,a),
  // small cartridge beside the bottle it refills
  cartridge: (f,a) => SV('<rect x="4" y="12" width="7" height="11" rx="2" fill="@a"/><path d="M6 12v-2h3v2" fill="@a"/>'
        + '<path d="M19 29h5a2 2 0 0 0 2-2V13a2 2 0 0 0-2-2h-5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2Z" fill="@f"/>'
        + '<path d="M17 16h9v5h-9Z" fill="@a" stroke="none" opacity=".9"/>'
        + '<path d="M20 11V8h3v3" fill="@a"/>'
        + '<path d="M12.5 17.5h3.5" fill="none" stroke="@a" stroke-dasharray="1.5 1.5"/>', f,a),
  // refillable metal case
  case: (f,a) => SV('<rect x="11" y="4" width="10" height="6" rx="2" fill="@a"/>'
        + '<path d="M11 10h10v16a3 3 0 0 1-3 3h-4a3 3 0 0 1-3-3V10Z" fill="@f"/>'
        + '<path d="M11 20h10v4H11Z" fill="@a" stroke="none" opacity=".75"/>', f,a),
  // tall liquid bottle
  bottle: (f,a) => SV('<path d="M12 29h8a2 2 0 0 0 2-2V15c0-2-2-2.4-2-4.5V9h-8v1.5c0 2.1-2 2.5-2 4.5v12a2 2 0 0 0 2 2Z" fill="@f"/>'
        + '<rect x="13" y="4" width="6" height="5" rx="1.6" fill="@a"/>'
        + '<path d="M10 18h12v5H10Z" fill="'+W+'" stroke="none"/>', f,a),
  // toothpaste tube
  tube: (f,a) => SV('<path d="M14 4h4v4h-4Z" fill="@a"/><path d="M12 12l2-4h4l2 4Z" fill="@f"/>'
        + '<path d="M12 12h8v13h-8Z" fill="@f"/><path d="M12 16h8v4h-8Z" fill="@a" stroke="none" opacity=".85"/>'
        + '<path d="M11 25h10v3H11Z" fill="@f"/>'
        + '<path d="M13.5 25v3M16 25v3M18.5 25v3" fill="none" stroke="rgba(0,0,0,.25)"/>', f,a),
  // solid bar
  bar: (f,a) => SV('<rect x="5" y="12" width="22" height="10" rx="4.5" fill="@f"/>'
        + '<rect x="5" y="15" width="22" height="4" fill="@a" stroke="none" opacity=".85"/>'
        + '<path d="M9 14c2.5-1 5-1 7.5 0" fill="none" stroke="rgba(255,255,255,.75)"/>', f,a),
  // bottle with a pump
  pump: (f,a) => SV('<path d="M12 29h8a2 2 0 0 0 2-2V15a2 2 0 0 0-2-2h-8a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2Z" fill="@f"/>'
        + '<path d="M10 19h12v5H10Z" fill="'+W+'" stroke="none"/>'
        + '<path d="M14 13v-3h4v3" fill="@a"/><path d="M16 10V6h4.5" fill="none" stroke="@a" stroke-width="1.5"/>', f,a),
  // refill pouch with a corner spout
  pouchspout: (f,a) => SV('<path d="M9 12h14v14a2 2 0 0 1-2 2H11a2 2 0 0 1-2-2Z" fill="@f"/>'
        + '<path d="M9 12l2-5h8l3 3.5v1.5Z" fill="@f"/>'
        + '<path d="M9 17h14v5H9Z" fill="'+W+'" stroke="none"/>'
        + '<path d="M22 10.5l2-1.5" fill="none" stroke="@a" stroke-width="1.4"/>'
        + '<rect x="23.5" y="6" width="3.5" height="3.5" rx="1" fill="@a"/>', f,a),
  // flat concentrate pouch
  pouch: (f,a) => SV('<path d="M10 6h12v20a2 2 0 0 1-2 2h-8a2 2 0 0 1-2-2Z" fill="@f"/>'
        + '<path d="M10 6h12v4.5H10Z" fill="@a" stroke="none"/>'
        + '<path d="M10 16h12v5H10Z" fill="'+W+'" stroke="none"/>'
        + '<path d="M22 12l-2.2 1.6 2.2 1.6" fill="none" stroke="rgba(0,0,0,.3)"/>', f,a),
  // small strong bottle, with the old big bottle as a dotted outline
  small: (f,a) => SV('<path d="M18 7h8v20a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2Z" fill="none" stroke="@f" '
        + 'stroke-dasharray="2 2" opacity=".45"/>'
        + '<path d="M7 29h5a2 2 0 0 0 2-2v-9a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2Z" fill="@f"/>'
        + '<path d="M5 21h9v4H5Z" fill="'+W+'" stroke="none"/>'
        + '<rect x="7.5" y="13.5" width="4" height="2.5" rx=".8" fill="@a"/>', f,a),
};

export const CASES = [
  {
    "id": 1,
    "icon": "spray",
    "pal": [
      "#2f7fae",
      "#15405c"
    ],
    "cat": "Home care · dish soap · 2020",
    "title": "Brisko Power Spray",
    "rows": [
      [
        "New",
        "The company puts the dish soap in a spray bottle. You spray the soap on the plate."
      ],
      [
        "Result",
        "The soap removes grease in half the time of the strongest other soap."
      ],
      [
        "Water",
        "You do not fill the sink. You do not open the tap."
      ],
      [
        "User task",
        "At each refill, you move the spray head to the new bottle."
      ],
      [
        "Price",
        "The price is 65 percent more than the usual soap of this company."
      ],
      [
        "Users say",
        "The price is too high."
      ]
    ]
  },
  {
    "id": 2,
    "icon": "cartridge",
    "pal": [
      "#dfe8ee",
      "#3f6783"
    ],
    "cat": "Home care · spray cleaner · 2020",
    "title": "Rezil Refill Cartridge",
    "rows": [
      [
        "New",
        "You keep your old bottle. You buy a small cartridge with strong cleaner."
      ],
      [
        "User task",
        "You remove the spray head. You fill the bottle with water to a line. You put the cartridge in. You close the bottle."
      ],
      [
        "Size",
        "The cartridge is very small and light. It uses little space."
      ],
      [
        "Price",
        "The cartridge costs less than a new bottle."
      ],
      [
        "Result",
        "The cleaner does the same job as before."
      ]
    ]
  },
  {
    "id": 3,
    "icon": "case",
    "pal": [
      "#f3edf0",
      "#c782ad"
    ],
    "cat": "Personal care · deodorant · 2021",
    "title": "Orva Steel Case",
    "rows": [
      [
        "New",
        "The company sells a deodorant in a metal case. You keep the case and buy refills."
      ],
      [
        "Quality",
        "The case is strong. The company replaces a broken case for all time, at no cost."
      ],
      [
        "Result",
        "The deodorant is the same as before."
      ],
      [
        "User task",
        "You keep the case. You put a refill in the case."
      ],
      [
        "Users say",
        "The stick comes off its base during use. The company agrees and sends free replacements."
      ],
      [
        "Price",
        "The case costs more than a usual deodorant."
      ]
    ]
  },
  {
    "id": 4,
    "icon": "bottle",
    "pal": [
      "#15b3b0",
      "#15293f"
    ],
    "cat": "Home care · laundry detergent · 2024",
    "title": "Quindo Cold 15",
    "rows": [
      [
        "New",
        "The company makes a detergent for short washes in cold water."
      ],
      [
        "Result",
        "In a 15 minute cold wash, the detergent removes dirt and smells that usual detergents leave."
      ],
      [
        "User task",
        "You use the same machine, the same drawer and the same quantity. Nothing changes."
      ],
      [
        "Price",
        "The price is more than the usual detergent of this company."
      ]
    ]
  },
  {
    "id": 5,
    "icon": "tube",
    "pal": [
      "#d9b98f",
      "#d12a24"
    ],
    "cat": "Personal care · toothpaste · 2020",
    "title": "Puralist Toothpaste",
    "rows": [
      [
        "New",
        "The toothpaste has few ingredients. 99 percent of them come from nature."
      ],
      [
        "Label",
        "The front of the pack shows each ingredient and its function."
      ],
      [
        "User task",
        "You clean your teeth as before. Nothing changes."
      ],
      [
        "Types",
        "There is one type only. There is no type for white teeth and no type for sensitive teeth."
      ],
      [
        "Price",
        "The price is more than the usual toothpaste of this company."
      ],
      [
        "Company says",
        "Later, the company said that the price was too high."
      ]
    ]
  },
  {
    "id": 6,
    "icon": "bar",
    "pal": [
      "#f2ccd6",
      "#057c44"
    ],
    "cat": "Personal care · hair care · 2020",
    "title": "Solibar Shampoo Bar",
    "rows": [
      [
        "New",
        "The company sells the shampoo as a solid bar in a paper box. There is no plastic bottle."
      ],
      [
        "Size",
        "The bar is much smaller and lighter than a bottle. It is easy to carry."
      ],
      [
        "User task",
        "You rub the bar on wet hair. You must learn a new method."
      ],
      [
        "Users say",
        "The bar needs more time to make foam. The wet bar makes dirt. There is no good place to put the bar."
      ],
      [
        "Price",
        "The price is near the price of a bottle."
      ]
    ]
  },
  {
    "id": 7,
    "icon": "pump",
    "pal": [
      "#a9d3c2",
      "#276361"
    ],
    "cat": "Personal care · hair care · 2023",
    "title": "Nuvern Nine Shampoo",
    "rows": [
      [
        "New",
        "The company makes a shampoo with nine ingredients only. It has no sulfates, no silicones and no colors."
      ],
      [
        "Result",
        "The shampoo keeps the same ingredient against dandruff. It works as before."
      ],
      [
        "Types",
        "The company sells the full group of types, as before."
      ],
      [
        "User task",
        "Same bottle, same method. Nothing changes."
      ],
      [
        "Price",
        "The price is more than the usual shampoo of this company."
      ]
    ]
  },
  {
    "id": 8,
    "icon": "pouchspout",
    "pal": [
      "#edc87b",
      "#086f3b"
    ],
    "cat": "Personal care · hair care · 2025",
    "title": "Ondara Refill Pouch",
    "rows": [
      [
        "New",
        "The company sells the shampoo in a soft pouch. You keep your old bottle."
      ],
      [
        "User task",
        "You open the pouch. You pour the shampoo into your old bottle."
      ],
      [
        "Product",
        "The shampoo is the same as before. The formula does not change."
      ],
      [
        "Price",
        "One pouch costs less than a new bottle."
      ],
      [
        "Material",
        "The pouch uses much less plastic than a bottle."
      ]
    ]
  },
  {
    "id": 9,
    "icon": "pouch",
    "pal": [
      "#4e9150",
      "#15381f"
    ],
    "cat": "Home care · dish soap · 2022",
    "title": "Shakel Dish Concentrate",
    "rows": [
      [
        "New",
        "You buy a small bag of strong soap and a bottle that you keep."
      ],
      [
        "User task",
        "At each refill, you fill the bottle with water, add the soap and shake the bottle."
      ],
      [
        "Size",
        "The bags are small and light. They are easy to keep."
      ],
      [
        "Price",
        "A bag costs less than a new bottle."
      ],
      [
        "Users say",
        "The soap does not mix fully. It makes lumps. The user must shake the bottle again."
      ],
      [
        "Types",
        "At the start, there is one smell only."
      ]
    ]
  },
  {
    "id": 10,
    "icon": "small",
    "pal": [
      "#5c2385",
      "#f6e27a"
    ],
    "cat": "Home care · floor cleaner · 2025",
    "title": "Tavro 10X Floor Gel",
    "rows": [
      [
        "New",
        "The company makes the cleaner very strong. The bottle is one fifth of the usual bottle."
      ],
      [
        "Routine",
        "Users of floor cleaner already put the cleaner in water. This routine does not change."
      ],
      [
        "User task",
        "The quantity changes. The company says that the first users did not know the correct quantity."
      ],
      [
        "Result",
        "You can also put the strong cleaner directly on difficult dirt. The usual cleaner cannot do this."
      ],
      [
        "Price",
        "For each use, the price is the same as the usual cleaner."
      ]
    ]
  }
];
