// GENERATED by split_cases.py — do not edit by hand.
// Public half: what a student may see. No outcomes live here.

const SV = (s,f,a) => '<svg viewBox="0 0 32 32" stroke="rgba(0,0,0,.30)" stroke-width="1.1" '
  + 'stroke-linejoin="round" stroke-linecap="round">'
  + s.replace(/@f/g, f).replace(/@a/g, a) + '</svg>';
const W = 'rgba(255,255,255,.88)';
export const ICONS = {
  // trigger spray bottle
  spray: (f,a) => SV('<path d="M12 29h8a2 2 0 0 0 2-2V16a2 2 0 0 0-2-2h-8a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2Z" fill="@f"/>'
        + '<path d="M10 19h12v4H10Z" fill="'+W+'" stroke="none"/>'
        + '<path d="M13.5 14v-3h5v3" fill="@a"/>'
        + '<path d="M15 11V7h5l2.5 2v2h-7Z" fill="@a"/>'
        + '<path d="M25.5 6.5l2-1M26 9h2M25.5 11.5l1.8 1" fill="none" stroke="@a" stroke-width="1.3"/>', f,a),
  // small cartridge beside the bottle it refills
  cartridge: (f,a) => SV('<rect x="4" y="12" width="7" height="11" rx="2" fill="@a"/><path d="M6 12v-2h3v2" fill="@a"/>'
        + '<path d="M19 29h5a2 2 0 0 0 2-2V13a2 2 0 0 0-2-2h-5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2Z" fill="@f"/>'
        + '<path d="M17 16h9v5h-9Z" fill="@a" stroke="none" opacity=".9"/>'
        + '<path d="M20 11V8h3v3" fill="@a"/>'
        + '<path d="M12.5 17.5h3.5" fill="none" stroke="@a" stroke-dasharray="1.5 1.5"/>', f,a),
  // refillable metal case
  case: (f,a) => SV('<rect x="11" y="4" width="10" height="6" rx="2" fill="@a"/>'
        + '<path d="M11 10h10v16a3 3 0 0 1-3 3h-4a3 3 0 0 1-3-3V10Z" fill="@f"/>'
        + '<path d="M11 20h10v4H11Z" fill="@a" stroke="none" opacity=".75"/>', f,a),
  // tall liquid bottle
  bottle: (f,a) => SV('<path d="M12 29h8a2 2 0 0 0 2-2V15c0-2-2-2.4-2-4.5V9h-8v1.5c0 2.1-2 2.5-2 4.5v12a2 2 0 0 0 2 2Z" fill="@f"/>'
        + '<rect x="13" y="4" width="6" height="5" rx="1.6" fill="@a"/>'
        + '<path d="M10 18h12v5H10Z" fill="'+W+'" stroke="none"/>', f,a),
  // toothpaste tube
  tube: (f,a) => SV('<path d="M14 4h4v4h-4Z" fill="@a"/><path d="M12 12l2-4h4l2 4Z" fill="@f"/>'
        + '<path d="M12 12h8v13h-8Z" fill="@f"/><path d="M12 16h8v4h-8Z" fill="@a" stroke="none" opacity=".85"/>'
        + '<path d="M11 25h10v3H11Z" fill="@f"/>'
        + '<path d="M13.5 25v3M16 25v3M18.5 25v3" fill="none" stroke="rgba(0,0,0,.25)"/>', f,a),
  // solid bar
  bar: (f,a) => SV('<rect x="5" y="12" width="22" height="10" rx="4.5" fill="@f"/>'
        + '<rect x="5" y="15" width="22" height="4" fill="@a" stroke="none" opacity=".85"/>'
        + '<path d="M9 14c2.5-1 5-1 7.5 0" fill="none" stroke="rgba(255,255,255,.75)"/>', f,a),
  // bottle with a pump
  pump: (f,a) => SV('<path d="M12 29h8a2 2 0 0 0 2-2V15a2 2 0 0 0-2-2h-8a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2Z" fill="@f"/>'
        + '<path d="M10 19h12v5H10Z" fill="'+W+'" stroke="none"/>'
        + '<path d="M14 13v-3h4v3" fill="@a"/><path d="M16 10V6h4.5" fill="none" stroke="@a" stroke-width="1.5"/>', f,a),
  // refill pouch with a corner spout
  pouchspout: (f,a) => SV('<path d="M9 12h14v14a2 2 0 0 1-2 2H11a2 2 0 0 1-2-2Z" fill="@f"/>'
        + '<path d="M9 12l2-5h8l3 3.5v1.5Z" fill="@f"/>'
        + '<path d="M9 17h14v5H9Z" fill="'+W+'" stroke="none"/>'
        + '<path d="M22 10.5l2-1.5" fill="none" stroke="@a" stroke-width="1.4"/>'
        + '<rect x="23.5" y="6" width="3.5" height="3.5" rx="1" fill="@a"/>', f,a),
  // flat concentrate pouch
  pouch: (f,a) => SV('<path d="M10 6h12v20a2 2 0 0 1-2 2h-8a2 2 0 0 1-2-2Z" fill="@f"/>'
        + '<path d="M10 6h12v4.5H10Z" fill="@a" stroke="none"/>'
        + '<path d="M10 16h12v5H10Z" fill="'+W+'" stroke="none"/>'
        + '<path d="M22 12l-2.2 1.6 2.2 1.6" fill="none" stroke="rgba(0,0,0,.3)"/>', f,a),
  // small strong bottle, with the old big bottle as a dotted outline
  small: (f,a) => SV('<path d="M18 7h8v20a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2Z" fill="none" stroke="@f" '
        + 'stroke-dasharray="2 2" opacity=".45"/>'
        + '<path d="M7 29h5a2 2 0 0 0 2-2v-9a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2Z" fill="@f"/>'
        + '<path d="M5 21h9v4H5Z" fill="'+W+'" stroke="none"/>'
        + '<rect x="7.5" y="13.5" width="4" height="2.5" rx=".8" fill="@a"/>', f,a),
};

export const CASES = [
  {
    "id": 1,
    "icon": "spray",
    "pal": [
      "#2f7fae",
      "#15405c"
    ],
    "cat": "Home care · dish soap · 2020",
    "title": "Brisko Power Spray",
    "desc": "A manufacturer of dish soap sells a spray format in place of a squeeze bottle. The user sprays the soap directly onto the item. The suds activate on contact, so the task needs no running water and no filled sink. The maker states that the formula removes grease in half the time of the strongest competing product. It also carries three cleaning agents that conventional dish liquids do not use. The product launched as a starter kit with a trigger head. Refills arrive as a plain bottle, and the trigger moves from the old bottle to the new one at each refill. The price is 30.9 cents for each fluid ounce. The conventional liquid from the same brand is 18.8 cents."
  },
  {
    "id": 2,
    "icon": "cartridge",
    "pal": [
      "#dfe8ee",
      "#3f6783"
    ],
    "cat": "Home care · spray cleaner · 2020",
    "title": "Rezil Refill Cartridge",
    "desc": "A manufacturer of household spray cleaner sells a concentrate cartridge for a bottle the customer already owns. At each refill the user removes the spray head and fills the bottle with tap water to a moulded line. The line marks 630 millilitres. The user then inserts the cartridge and closes the bottle. The cartridge holds a fraction of the volume of a full bottle and occupies little shelf or cupboard space. Transport weight falls in proportion. The cleaning formula is identical to the ready-mixed product. One cartridge costs less than one replacement bottle."
  },
  {
    "id": 3,
    "icon": "case",
    "pal": [
      "#f3edf0",
      "#c782ad"
    ],
    "cat": "Personal care · deodorant · 2021",
    "title": "Orva Steel Case",
    "desc": "A personal care company sells a deodorant in a refillable stainless steel case. The customer keeps the case and buys refill sticks for it. The case carries a warranty without end: the company replaces it or refunds it, and asks for no proof of purchase. The formula matches the conventional stick from the same brand. At each replacement the user inserts a refill into the case. After launch the company confirmed that the stick could separate from the applicator base during use, and it sent free replacement packs to buyers. The starter kit with the case costs more than a conventional stick."
  },
  {
    "id": 4,
    "icon": "bottle",
    "pal": [
      "#15b3b0",
      "#15293f"
    ],
    "cat": "Home care · laundry detergent · 2024",
    "title": "Quindo Cold 15",
    "desc": "A laundry detergent is formulated for short wash cycles at low temperature. The manufacturer states that conventional detergents leave invisible soil, and the compounds that cause body odour, when a cycle runs for a short time. This formula removes them in a cycle of fifteen minutes at thirty degrees. A short cold cycle draws less electricity than a long warm one. The dose, the dispenser drawer and the machine setting are the same as for the product it replaces. The detergent sells above the price of the standard range from the same brand."
  },
  {
    "id": 5,
    "icon": "tube",
    "pal": [
      "#d9b98f",
      "#d12a24"
    ],
    "cat": "Personal care · toothpaste · 2020",
    "title": "Puralist Toothpaste",
    "desc": "A toothpaste is formulated with a short ingredient list. The manufacturer states that 99.7 per cent of the content is of natural origin. The pack prints each ingredient and its function on the front. The tube is made from one material and enters standard recycling. Brushing is unchanged. The line holds a single variant. The brand's conventional range includes versions for whitening, for charcoal and for sensitive teeth, and this product offers none of them. It sells above the price of the conventional toothpaste from the same brand."
  },
  {
    "id": 6,
    "icon": "bar",
    "pal": [
      "#f2ccd6",
      "#057c44"
    ],
    "cat": "Personal care · hair care · 2020",
    "title": "Solibar Shampoo Bar",
    "desc": "A hair care company sells shampoo as a solid bar in a paperboard sleeve. The format removes the plastic bottle. The bar weighs less than a bottle that holds the same number of washes. It also takes less space in transport and in luggage. In use the customer rubs the bar on wet hair, or works it into a lather in the hands. Reviews record that the bar takes longer to produce a lather than liquid shampoo. They also record that the wet bar leaves residue on surfaces. The bar needs a separate stand or dish between uses. The price is close to the price of a bottle."
  },
  {
    "id": 7,
    "icon": "pump",
    "pal": [
      "#a9d3c2",
      "#276361"
    ],
    "cat": "Personal care · hair care · 2023",
    "title": "Nuvern Nine Shampoo",
    "desc": "An anti-dandruff shampoo is reformulated to nine ingredients. It carries no sulfates, no silicones and no added colour. The active ingredient that controls dandruff is the one used across the brand's conventional range, at the same concentration. The company sells the line in the full set of variants offered elsewhere in that range. The bottle, the pump and the washing method are unchanged. The product sells above the price of the brand's standard shampoos."
  },
  {
    "id": 8,
    "icon": "pouchspout",
    "pal": [
      "#edc87b",
      "#086f3b"
    ],
    "cat": "Personal care · hair care · 2025",
    "title": "Ondara Refill Pouch",
    "desc": "A hair care company sells shampoo in a flexible pouch, for refilling a bottle the customer already owns. The user opens the pouch and pours the contents into the bottle. The formula, the fragrance and the thickness match the bottled product. The pouch uses substantially less plastic by weight than a rigid bottle of the same volume, and it ships flat. One pouch costs less than one replacement bottle. The company does not always list the pouch as a separate product on its website."
  },
  {
    "id": 9,
    "icon": "pouch",
    "pal": [
      "#4e9150",
      "#15381f"
    ],
    "cat": "Home care · dish soap · 2022",
    "title": "Shakel Dish Concentrate",
    "desc": "A dish soap is sold as a concentrated gel in a small pouch, with a reusable bottle in the starter kit. At each refill the user fills the bottle with water, adds the concentrate, and shakes the bottle until the mixture combines. The pouches are flat and light and take little space in transport and in storage. A pouch costs less than a replacement bottle of ready-mixed liquid. Customer reviews record that the concentrate dissolves slowly, and that the mixture separates or forms lumps. The user must shake the bottle again before later use. The starter kit launched in a single fragrance."
  },
  {
    "id": 10,
    "icon": "small",
    "pal": [
      "#5c2385",
      "#f6e27a"
    ],
    "cat": "Home care · floor cleaner · 2025",
    "title": "Tavro 10X Floor Gel",
    "desc": "A floor cleaner is sold as a gel concentrated ten times. One bottle of twelve fluid ounces provides sixty uses, which matches more than seven bottles of the brand's original dilution. For the same number of uses the format carries ninety per cent less weight and uses eighty-three per cent less plastic. Customers in this category already dilute floor cleaner in a bucket, and that step is unchanged, but the quantity for each bucket is different. The company reports that buyers were uncertain about the correct dose in the period after launch. The gel can also be applied directly to heavy soil, which the previous dilution could not. The price for each use matches the existing product."
  }
];
